name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
    paths:
      - "content/**"    # Trigger for content changes
      - "layouts/**"    # Trigger for layout changes
      - "static/**"     # Trigger for static asset changes
      - "config.toml"   # Trigger for config changes
  workflow_dispatch: # Allow manual trigger

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      # Step 3: Build the Hugo site
      - name: Build site
        run: hugo --minify

      # Step 4: Deploy to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory to deploy
          publish_branch: gh-pages  # Branch to deploy to
